version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - django_network

  web:
    image: django_basic_setup_web
#    ports:
#      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=django_basic_setup.settings
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
    depends_on:
      - db
    networks:
      - django_network

  nginx:
    image: nginx:alpine
    volumes:
      - /home/cosme/repos_cesar_ovidio_gutierrez/django-basic-setup/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - django_network

volumes:
  postgres_data:

networks:
  django_network:
    driver: bridge
